version: '3.8'

services:

  climbing:
    image: steel8rat/climbing
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=build/libs/*.jar
    ports:
      - "8080:8080"