
spring:
  data:
    mongodb:
      host: 10.0.1.6
      port: 27017
      username: routesetter-admin
      password: kjh4ljh543kjh33h4
      authentication-database: admin
      database: routesetter
  main:
    banner-mode: 'off'