apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {

        types {
          text/html                             html htm shtml;
          text/css                              css;
          text/xml                              xml rss;
          image/gif                             gif;
          image/jpeg                            jpeg jpg;
          application/x-javascript              js;
          text/plain                            txt;
          text/x-component                      htc;
          text/mathml                           mml;
          image/png                             png;
          image/x-icon                          ico;
          image/x-jng                           jng;
          image/vnd.wap.wbmp                    wbmp;
          application/java-archive              jar war ear;
          application/mac-binhex40              hqx;
          application/pdf                       pdf;
          application/x-cocoa                   cco;
          application/x-java-archive-diff       jardiff;
          application/x-java-jnlp-file          jnlp;
          application/x-makeself                run;
          application/x-perl                    pl pm;
          application/x-pilot                   prc pdb;
          application/x-rar-compressed          rar;
          application/x-redhat-package-manager  rpm;
          application/x-sea                     sea;
          application/x-shockwave-flash         swf;
          application/x-stuffit                 sit;
          application/x-tcl                     tcl tk;
          application/x-x509-ca-cert            der pem crt;
          application/x-xpinstall               xpi;
          application/zip                       zip;
          application/octet-stream              deb;
          application/octet-stream              bin exe dll;
          application/octet-stream              dmg;
          application/octet-stream              eot;
          application/octet-stream              iso img;
          application/octet-stream              msi msp msm;
          audio/mpeg                            mp3;
          audio/x-realaudio                     ra;
          video/mpeg                            mpeg mpg;
          video/quicktime                       mov;
          video/x-flv                           flv;
          video/x-msvideo                       avi;
          video/x-ms-wmv                        wmv;
          video/x-ms-asf                        asx asf;
          video/x-mng                           mng;
        }

        default_type application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #ADDED
        gzip on;
        gzip_vary on;
        # gzip_proxied any;
        gzip_comp_level 7;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript application/octet-stream;

        #include /etc/nginx/conf.d/*.conf;

        #ADDED
        include /etc/nginx/virtualhost/virtualhost.conf;
    }
  virtualhost.conf: |
    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;
        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        # proxy api requests to api-server listening on api-server:8080
        #
        location /api {
            proxy_pass   http://api-server:8080;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: steel8rat/nginx:<TAG>
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx # mount nginx-conf volume to /etc/nginx
              readOnly: true
              name: nginx-conf
            - mountPath: /var/log/nginx
              name: log
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: virtualhost.conf
                path: virtualhost/virtualhost.conf # dig directory
        - name: log
          emptyDir: {}