name: Apps / Auth Build

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

    paths:
      - 'apps/auth'
      - '.github/workflows/auth-deploy.yml'
env:
  IMAGE_NAME: steel8rat/auth
  IMAGE_TAG: ${{ github.sha }} # take commit sha as a image tag

jobs:
  auth_build_and_deploy:
    name: Build Auth App
    runs-on: ubuntu-latest
    env:
      workingDirectory: ./apps/auth

    steps:
      - uses: actions/checkout@v2

      - name: Set up AdoptOpenJDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Set up gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        working-directory: ${{ env.workingDirectory }}
        run: ./gradlew build

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Artifacts
        run: ls -R
        working-directory: apps/auth/build/libs

      - name: Build Docker image
        run: docker build --build-arg JAR_FILE=apps/auth/build/libs/*-SNAPSHOT.jar --file apps/auth/Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG .

      - name: Push image to Dockerhub
        run: docker push $JDK_IMAGE:$IMAGE_TAG

      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: github # Optional. (defaults to webhook app)
          SLACK_CHANNEL: routesetter # Optional. (defaults to webhook)
          SLACK_AVATAR: https://cdn.routesetter.app/avatar/av0.jpg # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
        uses: Ilshidur/action-slack@master
        with:
          args: 'Auth App has been built'